development:
  password: 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
  theme_id: "159201886486"
  store: the-co-creative.myshopify.com
# theme new --password=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 --store=the-co-creative.myshopify.com --name=creative-professional